# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.3"
    }
  }

  required_version = ">= 1.1.0"

  backend "s3" {
    bucket         = "news-for-kids-baseline-terraform-state-058264124525-eu-north-1"
    key            = "lambda-cmd.tfstate"
    region         = "eu-north-1"
  }
}

provider "aws" {
  region              = "eu-north-1"
  allowed_account_ids = ["058264124525"]
  default_tags {
    tags = {
      Stack = "lambda-cmd"
    }
  }
}
